# Generated by Django 5.0.6 on 2024-06-09 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='last_updated',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='last_updated',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='last_updated',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='travelcategory',
            old_name='last_updated',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='travels',
            old_name='last_updated',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
